apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mkdocs
  name: mkdocs-data2
  namespace: del
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
