apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: backup
  name: pg-backup-data
  namespace: del
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
