name: Docker and Helm

on:
  release:
    types: [published]
  workflow_dispatch:
  
jobs:
  dockerbuild:
    uses: eclipse-xfsc/dev-ops/.github/workflows/dockerbuild.yml@main
    secrets: inherit
    with: 
      dockerfile: "Dockerfile"
      repo_name: del